-- CreateTable
CREATE TABLE "@pm25datas" (
    "id" SERIAL NOT NULL,
    "pm25_1" TEXT,
    "temp1" TEXT,
    "hum1" TEXT,
    "pres1" TEXT,
    "pm25_2" TEXT,
    "temp2" TEXT,
    "hum2" TEXT,
    "pres2" TEXT,
    "pm25_3" TEXT,
    "temp3" TEXT,
    "hum3" TEXT,
    "pres3" TEXT,
    "pm25_4" TEXT,
    "temp4" TEXT,
    "hum4" TEXT,
    "pres4" TEXT,
    "pm25_5" TEXT,
    "temp5" TEXT,
    "hum5" TEXT,
    "pres5" TEXT,
    "pm25_6" TEXT,
    "temp6" TEXT,
    "hum6" TEXT,
    "pres6" TEXT,
    "pm25_7" TEXT,
    "temp7" TEXT,
    "hum7" TEXT,
    "pres7" TEXT,
    "pm25_8" TEXT,
    "temp8" TEXT,
    "hum8" TEXT,
    "pres8" TEXT,
    "pm25_9" TEXT,
    "temp9" TEXT,
    "hum9" TEXT,
    "pres9" TEXT,
    "pm25_0" TEXT,
    "temp0" TEXT,
    "hum0" TEXT,
    "pres0" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "@pm25datas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "@co2s" (
    "id" SERIAL NOT NULL,
    "co2_1" TEXT,
    "temp1" TEXT,
    "hum1" TEXT,
    "pres1" TEXT,
    "co2_2" TEXT,
    "temp2" TEXT,
    "hum2" TEXT,
    "pres2" TEXT,
    "co2_3" TEXT,
    "temp3" TEXT,
    "hum3" TEXT,
    "pres3" TEXT,
    "co2_4" TEXT,
    "temp4" TEXT,
    "hum4" TEXT,
    "pres4" TEXT,
    "co2_5" TEXT,
    "temp5" TEXT,
    "hum5" TEXT,
    "pres5" TEXT,
    "co2_6" TEXT,
    "temp6" TEXT,
    "hum6" TEXT,
    "pres6" TEXT,
    "co2_7" TEXT,
    "temp7" TEXT,
    "hum7" TEXT,
    "pres7" TEXT,
    "co2_8" TEXT,
    "temp8" TEXT,
    "hum8" TEXT,
    "pres8" TEXT,
    "co2_9" TEXT,
    "temp9" TEXT,
    "hum9" TEXT,
    "pres9" TEXT,
    "co2_0" TEXT,
    "temp0" TEXT,
    "hum0" TEXT,
    "pres0" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "@co2s_pkey" PRIMARY KEY ("id")
);
